version: '3.8'

services:
  db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./data:/data
    command: server /data
  server:
    image: app
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    depends_on:
      - db
    ports:
      - "8090:8090"
    volumes:
      - .:/opt/app
    env_file:
      - .env
    restart: always
volumes:
  db:
    driver: local